import pathlib
import re
import subprocess
import sys
import tempfile
from pathlib import Path
import httpx
import platform

sys.path.append(str(pathlib.Path(__file__).parents[2]))

from core.config import config

# https://openapi-generator.tech/docs/usage


def download_openapi_json() -> None:
    with httpx.Client(timeout=60.0, follow_redirects=False) as client:
        url = f'{config.api_base_url}/openapi.json'
        print(config.api_base_url)
        response = client.get(url=url, headers={'Accept': 'application/json'}, timeout=60.0)
        response.raise_for_status()
    (Path(__file__).parents[2] / 'app' / 'openapi.json').write_bytes(response.content)


def extract_api_client(api_client_path: Path) -> str:
    """Extract the three self-contained static helpers the model classes use
    (convertToType/parseDate/constructFromObject) from the generated
    ApiClient.js, dropping the HTTP client part (superagent dependency)."""
    source = api_client_path.read_text()
    methods = []
    for name in ('parseDate', 'convertToType', 'constructFromObject'):
        match = re.search(rf'    static {name}\(.*?\n    \}}', source, re.DOTALL)
        if not match:
            raise RuntimeError(f'static {name}() not found in generated ApiClient.js')
        methods.append(match.group(0))
    return 'export class ApiClient {\n' + '\n\n'.join(methods) + '\n}\n'


def bundle_model(source: str) -> str:
    source = re.sub(r'\A/\*\*.*?\*/\s*', '', source, flags=re.DOTALL)  # per-file license header
    source = re.sub(r'^import .*\n', '', source, flags=re.MULTILINE)  # classes live in one module
    source = source.replace('export default class ', 'export class ')
    source = re.sub(r'^export default (\w+);', r'export { \1 };', source, flags=re.MULTILINE)
    return source.strip() + '\n'


def generate_models_openapi() -> None:
    input_path = Path(__file__).parents[2] / 'app' / 'openapi.json'
    output_path = Path(__file__).parents[2] / 'app' / 'openapi.js'
    with tempfile.TemporaryDirectory() as tmp:
        # The Java-based generator parses the input path as a URI and fails on the
        # spaces in the repo path — work on a copy of the spec in the temp dir.
        tmp_spec = Path(tmp) / 'openapi.json'
        tmp_spec.write_bytes(input_path.read_bytes())
        out_dir = Path(tmp) / 'out'
        # List args (no shell): the CLI's console script is not on PATH — call its
        # entry point via the running interpreter (the package has no __main__,
        # so `-m openapi_generator_cli` does not work).
        if platform.system() == 'Linux':
            cmd = ['uv', 'run', 'openapi-generator-cli',
                   'generate', '-i', str(tmp_spec), '-g', 'javascript', '-o', str(out_dir),
                   '--global-property', 'models,supportingFiles,modelDocs=false,modelTests=false']
        else:
            cmd = [sys.executable, '-c', 'from openapi_generator_cli import cli; cli()',
                   'generate', '-i', str(tmp_spec), '-g', 'javascript', '-o', str(out_dir),
                   '--global-property', 'models,supportingFiles,modelDocs=false,modelTests=false']
        print(subprocess.list2cmdline(cmd))
        subprocess.run(cmd, check=True)
        header = (f'// Auto-generated by core/openapi/build_openapi_models_js.py - do not edit.\n'
                  f'// Source: {config.api_base_url}/openapi.json, converted with OpenAPI Generator\n'
                  f'// (https://openapi-generator.tech), bundled into one ES module with named exports.\n')
        parts = [header, extract_api_client(out_dir / 'src' / 'ApiClient.js')]
        for model_file in sorted((out_dir / 'src' / 'model').iterdir()):
            parts.append(bundle_model(model_file.read_text()))

    output_path.write_text('\n'.join(parts))
    print(f'{output_path} ({len(parts) - 2} model classes)')


if __name__ == '__main__':
    download_openapi_json()
    generate_models_openapi()
